### ISSUE TITLE
switch azure static web apps development accounts soon?

### ISSUE THREAD

**Issue by illume** [Smithsonian/ForestGEO#101]
Do we need to switch the azure static web apps accounts soon? I think @OmarShehata mentioned so.

We can use some free azure credits I have allocated to me we can use for development.

Later on when it switches into production, we'll need to organize a ForestGEO/Smithsonian account.

Probably we have to change the tokens inside github -> settings -> secrets, and maybe some config in .github/workflows/azure-static-web-apps-agreeable-wave-08a957210.yml (I think that's it?)

**Comment by esscott** [comment]
Yes, that would be great @illume! I wonder if we need @zmagar to approve this change from his account (which is currently funded through CodeDay)?

**Comment by illume** [comment]
It seems the web app is kind of not working on the Browse page anymore. It just returns a 500 error.

I'll prioritize moving this over (after a few other tasks).

**Comment by OmarShehata** [comment]
The browse page still works for me, just tested now: https://agreeable-wave-08a957210.1.azurestaticapps.net/browse. I can see data returned when selected cocoli.

It's possible there's an edge case that's not handled when a different user is logged in. I still have Azure access through CodeDay if you need anything for this transition @illume @esscott . There should be server logs that will tell us why the 500's are happening.

**Comment by illume** [comment]
Aha! It works for me now. Must have just been a temporary glitch or something I did wrong.

Thanks for looking into it :)

**Comment by illume** [comment]
Ah, the problem persists in the one made from this PR: https://github.com/ForestGeoHack/ForestGEO/pull/108
https://agreeable-wave-08a957210-108.centralus.1.azurestaticapps.net/browse

It works for me on your link only. The request it makes is the same, but on that PR there is the 500 error. Indeed, could be something like different user related like you suggest.

I don't think we require anything for the transition. I expect just setting it up on a different account is all that's required. But what do I know? haha. I hope I can get it done without bothering you... *fingers crossed* :)
