### ISSUE TITLE
minMaxHeightOfMeasure validation

### ISSUE THREAD

**Issue by illume** [Smithsonian/ForestGEO#129]
See "[instructions for writing a validation function](https://github.com/ForestGeoHack/ForestGEO/issues/107#issuecomment-1345698975)". Below are notes from the spec.

minMaxHeightOfMeasure  Min & Max Height of Measurement (HOM) | *NEW ADDITION* |   | Makes sure HOM is within range for a given site. Must be greater than 0. Usually HOM is at “breast height” approximately 1.3m.
-- | -- | -- | --

Note, this is a new validation without an existing validation function.

**Comment by siddheshraze** [comment]
Here is an updated procedure to run this and mark its errors in the CMVErrors table! Function's been reviewed with GPT so it _should_ work as intended, but full testing is still pending:

```tsql
create
    definer = azureroot@`%` procedure ValidateHOMUpperAndLowerBounds(IN minHOM decimal(10, 2), IN maxHOM decimal(10, 2))
BEGIN
    INSERT INTO forestgeo_bci.cmverrors (CoreMeasurementID, ValidationErrorID)
    SELECT
        CoreMeasurementID,
        3 AS ValidationErrorID
    FROM
        forestgeo_bci.coremeasurements
    WHERE
        MeasuredHOM < minHOM OR MeasuredHOM > maxHOM;
END;


```

**Comment by justinpac** [comment]
Same as screenDiam - there's some uncertainty about whether this is still needed. @siddheshraze  to follow up with Stuart and Suzanne over email.

**Comment by justinpac** [comment]
Deleted because we got feedback that this validation is not needed.
