### ISSUE TITLE
Need to Create and Populate Azure KeyVault for Secrets Storage

### ISSUE THREAD

**Issue by siddheshraze** [Smithsonian/ForestGEO#146]
Needs to work in tandem with moving to live site --> live site needs to use env vars stored in Keyvault instead of locally

**Comment by justinpac** [comment]
In https://portal.azure.com/#@SIOCIORC.onmicrosoft.com/resource/subscriptions/6b21b577-e408-4d46-8749-b67b37f08b9c/resourceGroups/forestgeo-rg/providers/Microsoft.KeyVault/vaults/forestgeo-app-key-vault/secrets
