### ISSUE TITLE
Administrator-Restricted Validation CRUD system

### ISSUE THREAD

**Issue by siddheshraze** [Smithsonian/ForestGEO#149]
Admins should be able to add/edit validation scripts as needed! 
1. need place to store scripts/load scripts
2. need way to connect scripts to inbound data??
3. need landing page for confirmation of run of new validation script(s)

(somewhat lower priority than other goals, stretch)

**Comment by justinpac** [comment]
For Jan 24 deadline, make it easy for someone to create a PR with a data validation script. Suggestion: structure the code such that each validation is one file. There's a pattern called the decorator pattern that may be applicable here.

**Comment by justinpac** [comment]
In frontend/app/(hub)/measurementshub/validations/page.tsx
