### ISSUE TITLE
running new frontend locally?

### ISSUE THREAD

**Issue by illume** [Smithsonian/ForestGEO#155]
Are there any more instructions to run it? I see this README section, but I guess maybe it needs a DB or something ? https://github.com/Smithsonian/ForestGEO/blob/main/frontend/README.md#running-the-project

Any other tips to get going locally?

Does it depend on my setting up some Azure things?

**Comment by justinpac** [comment]
@siddheshraze  could you add on here?

**Comment by justinpac** [comment]
This PR adds a readme that is easy to follow: https://github.com/Smithsonian/ForestGEO/pull/182/files
