### ISSUE TITLE
Add in-line error component 

### ISSUE THREAD

**Issue by esscott** [Smithsonian/ForestGEO#39]
As a data entry person, I want to see any errors associated with a specific data point displayed directly in-line with an error code and description of what's wrong, so that I can easily identify what needs correcting and whether it's a typo that I can fix at my desk or something that needs to be checked in the field.

Use Storybook #36 to create and test in-line error component without proper backend.

![](https://user-images.githubusercontent.com/43100092/169610999-bf7be3d1-3a7d-45ef-bdee-371a54d343a0.jpg)

**Comment by illume** [comment]
Seems like the error message was added in this PR: https://github.com/ForestGeoHack/ForestGEO/pull/71

It's not as a separate component though. So the remaining work on this issue would be to move it into a separate component.
