### ISSUE TITLE
Add file list page

### ISSUE THREAD

**Issue by esscott** [Smithsonian/ForestGEO#41]
As a data entry person, I want to browse a list of previously uploaded CSV files, so that I can keep track of the work my team has done on a particular census and manage duplicate data.

- [ ] File list is organized by form type, quadrat number, date entered, who it was entered by, validation status, and any other relevant, distinguishing meta data
- [ ] File list is mutable with edit and delete actions available

![](https://user-images.githubusercontent.com/43100092/169611038-1e8c8150-ef0d-4a91-8408-50bed59970fd.jpg)

**Comment by esscott** [comment]
Please see commit 9fe746e90c70d756b341603cc4e523531e419609 and `esscott/file-browser` branch for starter code.

**Comment by Jaro05** [comment]
The main outline of this issue has been solved. There is now a browse page with a delete icon. However, it must be connected to the backend and the download and edit functionality still has to be changed

**Comment by OmarShehata** [comment]
@Jaro05 we can go ahead and close this issue and open up a new one for the backend portion of this. Thanks!
