### ISSUE TITLE
Add Changelog

### ISSUE THREAD

**Issue by esscott** [Smithsonian/ForestGEO#43]
As a data entry person, after I make corrections to my data according to the error report and re-upload the CSV, I want this revised version to replace the old version, so that the data remains organized and duplicate free.

- [ ] User is required to click to confirm replacement action
- [ ] Implement version control methods to "soft" delete (mark as deleted but retain data until a certain point)

**Comment by justinpac** [comment]
Data should not be immutable. A Change log has already been implemented but we need to demo it to ensure it is what Stuart et al want.

**Comment by justinpac** [comment]
This is available on the dashboard, but it only shows the five most recent changes. We don't have a view for every change:

![image](https://github.com/user-attachments/assets/50eb8d86-63b2-4116-8c1b-5bfce0bac0a3)

This is what it looks like in SQL:

![image](https://github.com/user-attachments/assets/ef005502-d638-4c06-8311-3b0dd66e6f9f)

**Comment by justinpac** [comment]
Keeping this open until a full view is implemented, but it's not a top priority.

**Comment by justinpac** [comment]
Unifiedchangelog has a log of all data changes in the table.
Open question: will this make data too big? We could delete changes after a certain number of days.
