### ISSUE TITLE
Update Dropzone to accept/process multiple CSV files simultaneously

### ISSUE THREAD

**Issue by esscott** [Smithsonian/ForestGEO#44]
As a data entry person, I want the option to upload multiple CSV files of data (each containing one or more quadrats) simultaneously, so that I can complete the entry and validation process more efficiently.

**Comment by gabriellaarcilla** [comment]
I think this issue may have been solved already.
I ran the code and I was able to upload multiple CSV files (each containing multiple quadrats) simultaneously, without any errors.
Is there something else I need to fix?

**Comment by zmagar** [comment]
Yeah, it looks like Dropzone component + FileReader support upload of multiple files simultaneously by default.

**Comment by illume** [comment]
Cool, looks like this one is done.
