### ISSUE TITLE
Update the app's title

### ISSUE THREAD

**Issue by OmarShehata** [Smithsonian/ForestGEO#50]
_This is a good first issue to get familiar with the project_.

Right now the app's title is "React App". We should change this to "Forest Geo" or something similar. 

It looks like you can't just add a `<title>` tag in React, and we may need to use something like this: https://github.com/nfl/react-helmet

**Comment by Aryan-Bhatt-pro** [comment]
is it done? or i can still contribute

**Comment by zmagar** [comment]
Almost done
