### ISSUE TITLE
Sample CSV files?

### ISSUE THREAD

**Issue by OmarShehata** [Smithsonian/ForestGEO#52]
@esscott is there somewhere we can get access to/store some sample CSV that show what the data that users of the app would be uploading? 

This is somewhat related to https://github.com/ForestGeoHack/ForestGEO/issues/38 but this is more to see examples of valid data that we can test with during development. 

Would be nice to have a `/data` folder in the repo with a couple of examples

**Comment by esscott** [comment]
To anyone working on this, please see CodeDay Slack message for files. https://codedayorg.slack.com/archives/C03LVLJTZHD/p1657054825664169

**Comment by illume** [comment]
Closing this one since the question was answered.

(Perhaps we can add some sample CSV files later to the repo. There's an issue for that here: https://github.com/ForestGeoHack/ForestGEO/issues/38)
