### ISSUE TITLE
Prototype CSV upload using Azure backend

### ISSUE THREAD

**Issue by OmarShehata** [Smithsonian/ForestGEO#54]
Assuming we're using Azure Function Apps as our backend (see https://github.com/ForestGeoHack/ForestGEO/issues/53), we should prototype a simple flow for uploading & retrieving CSV files, so we can understand how this works, since this is the main data requirement of the app.

I think we will want to use Azure blob storage for this:

https://docs.microsoft.com/en-us/azure/storage/blobs/storage-blobs-introduction

So the backend/function app API should have (1) a POST route that can take a file & some metadata (the username of who uploaded it etc) (2) a route to download the file given some identifier

Wiring this up to the frontend can be a follow up task.

**Comment by illume** [comment]
This was done, so closing this now.
