### ISSUE TITLE
Design Backend Architecture diagram

### ISSUE THREAD

**Issue by zmagar** [Smithsonian/ForestGEO#77]
As a developer, I want to see and visualize how the proposed solution looks like, what backend services we are going to use and how they are connected between each other.

**Comment by OmarShehata** [comment]
Related, see architecture diagram here: https://github.com/ForestGeoHack/ForestGEO/wiki/ForestGEO-App-Specification#architecture-proposal

**Comment by illume** [comment]
I guess we're clear about what backend services are being made now?

Closing.
(If there's something else needed, feel free to reopen :)
