### ISSUE TITLE
Alex's Developer Log

### ISSUE THREAD

**Issue by zmagar** [Smithsonian/ForestGEO#87]
### 8/15
Starting to log my work for the project. Discussed next steps with Omar:
- For security and other reasons change the upload function by creating an API route that will lead to Azure function on the server, which in turn will do the validation and the upload
- some old Azure Functions APIs from Prototypes folder were causing issues when I was creating Azure API for our Static web app , I removed them in my ab-functions branch but Omar asked to create a separate issue for that, need to restore the files in my current branch.
- need to make a drop-down menu to choose a plot where to upload file(s)
- after that work on getting data from a single plot, as a first step show contents of the first file, then if the plot has several files, combine them, if they have the same rows, take data from the one uploaded later.
### 8/16
Went through several tutorials on Azure Functions to understand the structure and the logic to apply it when redesigning the upload function. Had issues with connecting local Azure Storage emulator (Azurite) for testing purposes but finally it's working. 
### 8/17
The upload function works via API, need to create API route and add the code with Blob SDK to the function to process files.  Restored Prototypes folder, it seems like after the Functions API folder was defined (/API) issues disappeared, so I'll keep the folder for now.
### 8/22
Okay, I finally figured it out, at least to the point that it works now. The problem was to use the parsed files from multipart component (they have the next fields: name, filename, FileBuffer, encoding, mimeType) to send it to blobUpload, The hard part for me was: to understand how to work with buffer and files in Nodejs; how to process the parsed files, save them in array(not necessary) and preserve the original file name and csv extension. I tried various options, from using NodeJS file system (storing a file and reading its contents), to uploading a file buffer to Azure storage (Blob upload function supports uploading buffers and strings), but finally I found a simpler solution, sending the array with parsed objects to our blobUpload function  and rewrote it to process them.
Also I moved sensitive variables like Azure Connection String to .env file, will share it in Slack to test Azure storage.
I created blob containers with names of all plots.
Need to figure out how to use Response from SDK blobClient upload function because now when I test the staged version online, it doesn't have a connection string but it sends 500 Internal Server Error instead of more specific error.
PR is ready, it is not ideal but I'm working on the next steps already (choose plot)

### 8/29 Update for the whole week
I worked on the component to implement a plot selection for upload. I created a hard-coded array of plots , including the number of a plot that I found on https://forestgeo.si.edu (it can be convenient to use numbers instead of names because Azure storage limits characters in containers' names. For now, I compare chosen plot name with containers names by removing all non-letter characters.  I added metadata to Cocoli container in Azure but for some reason when I pull the metadata is shows as undefined.

**Comment by OmarShehata** [comment]
Next milestones:

Upload & authentication
  * An API route that is given CSV file(s) and can add them to blob storage
  * Add `plotId` as a parameter to this upload API route. If `plotId` is not in a list of pre-defined plots, refuse to upload, return `401` error
    * Can hard-code list of known plots for now 
  * Get the user in the upload API route. If the user does not have access to this plot (can hard-code a map for now) then refuse to upload, return `401`

Loading the data
  * Make an API route `getDataForPlot` that is given a plotID and returns a list of all the filenames uploaded for that plot
    * BUT if a user does not have access to this plotID, return `401` 
  * Then make `getDataForPlot` read the CSV file data, and return the rows, not just the names of the files
  * Finally, make it combine all the data

After this: basic validation on upload

**Comment by illume** [comment]
I guess we can close this one now.
